import { createPersistentStore } from "@/lib/store";

export interface FavoriteItem {
  id: string;
  /** "sermon" = item from category, "draft" = generated by user */
  kind: "sermon" | "draft";
  title: string;
  excerpt?: string;
  category?: string;
  /** Category slug for in-app navigation back to the category page. */
  categorySlug?: string;
  /** Sermon id (for category items). */
  sermonId?: string;
  addedAt: string;
}

const store = createPersistentStore<FavoriteItem[]>("favorites/v2", []);

export const favoritesStore = {
  use: store.use,
  list: () => store.get(),
  isFavorite: (id: string) => store.get().some((f) => f.id === id),
  toggle: (item: Omit<FavoriteItem, "addedAt">): boolean => {
    const existing = store.get().some((f) => f.id === item.id);
    if (existing) {
      store.set((p) => p.filter((f) => f.id !== item.id));
      return false;
    }
    store.set((p) => [{ ...item, addedAt: new Date().toISOString() }, ...p]);
    return true;
  },
  remove: (id: string) => store.set((p) => p.filter((f) => f.id !== id)),
  clear: () => store.set([]),
};
