/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppSavedIndexRouteImport } from './routes/app.saved.index'
import { Route as AppCategoriesIndexRouteImport } from './routes/app.categories.index'
import { Route as AppSavedIdRouteImport } from './routes/app.saved.$id'
import { Route as AppCategoriesSlugRouteImport } from './routes/app.categories.$slug'
import { Route as ApiPublicHdithProxyRouteImport } from './routes/api/public/hdith-proxy'
import { Route as AppCategoriesSlugIndexRouteImport } from './routes/app.categories.$slug.index'
import { Route as AppCategoriesSlugSermonIdRouteImport } from './routes/app.categories.$slug.$sermonId'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIndexRoute = AppSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedIdRoute = AppSavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesSlugRoute = AppCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHdithProxyRoute = ApiPublicHdithProxyRouteImport.update({
  id: '/api/public/hdith-proxy',
  path: '/api/public/hdith-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoriesSlugIndexRoute = AppCategoriesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCategoriesSlugRoute,
} as any)
const AppCategoriesSlugSermonIdRoute =
  AppCategoriesSlugSermonIdRouteImport.update({
    id: '/$sermonId',
    path: '/$sermonId',
    getParentRoute: () => AppCategoriesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workshop': typeof WorkshopRoute
  '/app/create': typeof AppCreateRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hdith-proxy': typeof ApiPublicHdithProxyRoute
  '/app/categories/$slug': typeof AppCategoriesSlugRouteWithChildren
  '/app/saved/$id': typeof AppSavedIdRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/saved/': typeof AppSavedIndexRoute
  '/app/categories/$slug/$sermonId': typeof AppCategoriesSlugSermonIdRoute
  '/app/categories/$slug/': typeof AppCategoriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workshop': typeof WorkshopRoute
  '/app/create': typeof AppCreateRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/public/hdith-proxy': typeof ApiPublicHdithProxyRoute
  '/app/saved/$id': typeof AppSavedIdRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/saved': typeof AppSavedIndexRoute
  '/app/categories/$slug/$sermonId': typeof AppCategoriesSlugSermonIdRoute
  '/app/categories/$slug': typeof AppCategoriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/workshop': typeof WorkshopRoute
  '/app/create': typeof AppCreateRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hdith-proxy': typeof ApiPublicHdithProxyRoute
  '/app/categories/$slug': typeof AppCategoriesSlugRouteWithChildren
  '/app/saved/$id': typeof AppSavedIdRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/saved/': typeof AppSavedIndexRoute
  '/app/categories/$slug/$sermonId': typeof AppCategoriesSlugSermonIdRoute
  '/app/categories/$slug/': typeof AppCategoriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/workshop'
    | '/app/create'
    | '/app/favorites'
    | '/app/history'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/api/public/hdith-proxy'
    | '/app/categories/$slug'
    | '/app/saved/$id'
    | '/app/categories/'
    | '/app/saved/'
    | '/app/categories/$slug/$sermonId'
    | '/app/categories/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/workshop'
    | '/app/create'
    | '/app/favorites'
    | '/app/history'
    | '/app/profile'
    | '/app/settings'
    | '/app'
    | '/api/public/hdith-proxy'
    | '/app/saved/$id'
    | '/app/categories'
    | '/app/saved'
    | '/app/categories/$slug/$sermonId'
    | '/app/categories/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/workshop'
    | '/app/create'
    | '/app/favorites'
    | '/app/history'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/api/public/hdith-proxy'
    | '/app/categories/$slug'
    | '/app/saved/$id'
    | '/app/categories/'
    | '/app/saved/'
    | '/app/categories/$slug/$sermonId'
    | '/app/categories/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  WorkshopRoute: typeof WorkshopRoute
  ApiPublicHdithProxyRoute: typeof ApiPublicHdithProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved/': {
      id: '/app/saved/'
      path: '/saved'
      fullPath: '/app/saved/'
      preLoaderRoute: typeof AppSavedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/': {
      id: '/app/categories/'
      path: '/categories'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved/$id': {
      id: '/app/saved/$id'
      path: '/saved/$id'
      fullPath: '/app/saved/$id'
      preLoaderRoute: typeof AppSavedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/$slug': {
      id: '/app/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/app/categories/$slug'
      preLoaderRoute: typeof AppCategoriesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hdith-proxy': {
      id: '/api/public/hdith-proxy'
      path: '/api/public/hdith-proxy'
      fullPath: '/api/public/hdith-proxy'
      preLoaderRoute: typeof ApiPublicHdithProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/categories/$slug/': {
      id: '/app/categories/$slug/'
      path: '/'
      fullPath: '/app/categories/$slug/'
      preLoaderRoute: typeof AppCategoriesSlugIndexRouteImport
      parentRoute: typeof AppCategoriesSlugRoute
    }
    '/app/categories/$slug/$sermonId': {
      id: '/app/categories/$slug/$sermonId'
      path: '/$sermonId'
      fullPath: '/app/categories/$slug/$sermonId'
      preLoaderRoute: typeof AppCategoriesSlugSermonIdRouteImport
      parentRoute: typeof AppCategoriesSlugRoute
    }
  }
}

interface AppCategoriesSlugRouteChildren {
  AppCategoriesSlugSermonIdRoute: typeof AppCategoriesSlugSermonIdRoute
  AppCategoriesSlugIndexRoute: typeof AppCategoriesSlugIndexRoute
}

const AppCategoriesSlugRouteChildren: AppCategoriesSlugRouteChildren = {
  AppCategoriesSlugSermonIdRoute: AppCategoriesSlugSermonIdRoute,
  AppCategoriesSlugIndexRoute: AppCategoriesSlugIndexRoute,
}

const AppCategoriesSlugRouteWithChildren =
  AppCategoriesSlugRoute._addFileChildren(AppCategoriesSlugRouteChildren)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesSlugRoute: typeof AppCategoriesSlugRouteWithChildren
  AppSavedIdRoute: typeof AppSavedIdRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppSavedIndexRoute: typeof AppSavedIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoriesSlugRoute: AppCategoriesSlugRouteWithChildren,
  AppSavedIdRoute: AppSavedIdRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppSavedIndexRoute: AppSavedIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  WorkshopRoute: WorkshopRoute,
  ApiPublicHdithProxyRoute: ApiPublicHdithProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
